// Vercel Edge Function for ADHDGoFly Plugin Data Collection
// 支持自定义域名，避免被墙问题

export default async function handler(request) {
  // 设置 CORS 头，允许跨域访问
  const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type, Authorization',
    'Content-Type': 'application/json'
  };

  // 处理 OPTIONS 预检请求
  if (request.method === 'OPTIONS') {
    return new Response(null, {
      status: 200,
      headers: corsHeaders
    });
  }

  // 只允许 POST 请求
  if (request.method !== 'POST') {
    return new Response(JSON.stringify({
      success: false,
      error: 'Method not allowed'
    }), {
      status: 405,
      headers: corsHeaders
    });
  }

  try {
    // 解析请求数据
    const data = await request.json();
    
    // 数据验证
    if (!data.action || !data.timestamp) {
      return new Response(JSON.stringify({
        success: false,
        error: 'Missing required fields: action, timestamp'
      }), {
        status: 400,
        headers: corsHeaders
      });
    }

    // 增强数据收集
    const enhancedData = {
      ...data,
      // 服务器时间戳
      serverTimestamp: new Date().toISOString(),
      // 用户IP (Vercel 提供)
      userIP: request.headers.get('x-forwarded-for') || 
              request.headers.get('x-real-ip') || 
              'unknown',
      // 用户代理
      userAgent: request.headers.get('user-agent') || 'unknown',
      // 地理位置 (Vercel 提供)
      country: request.headers.get('x-vercel-ip-country') || 'unknown',
      city: request.headers.get('x-vercel-ip-city') || 'unknown',
      // 请求ID
      requestId: crypto.randomUUID()
    };

    // 可选：存储到 GitHub (如果配置了 GITHUB_TOKEN)
    const githubToken = process.env.GITHUB_TOKEN;
    if (githubToken) {
      try {
        await storeToGitHub(enhancedData, githubToken);
      } catch (error) {
        console.error('GitHub storage failed:', error);
        // 不影响主要功能，继续执行
      }
    }

    // 记录到 Vercel 日志 (免费且永久可查)
    console.log('ADHDGoFly Data:', JSON.stringify(enhancedData, null, 2));

    // 返回成功响应
    return new Response(JSON.stringify({
      success: true,
      message: 'Data collected successfully',
      requestId: enhancedData.requestId,
      timestamp: enhancedData.serverTimestamp
    }), {
      status: 200,
      headers: corsHeaders
    });

  } catch (error) {
    console.error('Collection error:', error);
    
    return new Response(JSON.stringify({
      success: false,
      error: 'Internal server error',
      message: error.message
    }), {
      status: 500,
      headers: corsHeaders
    });
  }
}

// 可选：存储到 GitHub Issues
async function storeToGitHub(data, token) {
  const owner = 'burenweiye'; // 替换为你的 GitHub 用户名
  const repo = 'ADHDGoFly-Plugin'; // 替换为你的仓库名
  
  const issueTitle = `Data Collection - ${data.action} - ${new Date().toISOString().split('T')[0]}`;
  const issueBody = `
## ADHDGoFly Plugin Data Collection

**Action:** ${data.action}
**Timestamp:** ${data.timestamp}
**Server Timestamp:** ${data.serverTimestamp}
**Request ID:** ${data.requestId}

### User Information
- **IP:** ${data.userIP}
- **Country:** ${data.country}
- **City:** ${data.city}
- **User Agent:** ${data.userAgent}

### Additional Data
\`\`\`json
${JSON.stringify(data, null, 2)}
\`\`\`

---
*Auto-generated by ADHDGoFly Plugin Data Collection System*
  `;

  const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/issues`, {
    method: 'POST',
    headers: {
      'Authorization': `token ${token}`,
      'Content-Type': 'application/json',
      'User-Agent': 'ADHDGoFly-Plugin-Collector'
    },
    body: JSON.stringify({
      title: issueTitle,
      body: issueBody,
      labels: ['data-collection', 'auto-generated']
    })
  });

  if (!response.ok) {
    throw new Error(`GitHub API error: ${response.status}`);
  }

  return await response.json();
}