// Vercel Serverless Function for ADHDGoFly Plugin Data Collection
// 支持自定义域名，避免被墙问题

export default async function handler(req, res) {
  // 设置 CORS 头，允许跨域访问
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');

  // 处理 OPTIONS 预检请求
  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  // 只允许 POST 请求
  if (req.method !== 'POST') {
    return res.status(405).json({
      success: false,
      error: 'Method not allowed'
    });
  }

  try {
    // 解析请求数据
    const data = req.body;
    console.log('📥 收到数据收集请求:', { 
        method: req.method,
        url: req.url,
        headers: Object.fromEntries(Object.entries(req.headers).filter(([key]) => 
            ['content-type', 'user-agent', 'x-forwarded-for', 'x-vercel-ip-country'].includes(key.toLowerCase())
        )),
        bodyKeys: Object.keys(data)
    });
    
    // 数据验证
    if (!data.action || !data.timestamp) {
        console.warn('❌ 数据验证失败: 缺少必要字段', { 
            hasAction: !!data.action, 
            hasTimestamp: !!data.timestamp,
            dataKeys: Object.keys(data)
        });
        return res.status(400).json({
            success: false,
            error: 'Missing required fields: action, timestamp'
        });
    }

    // 增强数据收集
    const enhancedData = {
      ...data,
      // 服务器时间戳
      serverTimestamp: new Date().toISOString(),
      // 用户IP (Vercel 提供)
      userIP: req.headers['x-forwarded-for'] || 
              req.headers['x-real-ip'] || 
              req.connection?.remoteAddress ||
              'unknown',
      // 用户代理
      userAgent: req.headers['user-agent'] || 'unknown',
      // 地理位置 (Vercel 提供)
      country: req.headers['x-vercel-ip-country'] || 'unknown',
      city: req.headers['x-vercel-ip-city'] || 'unknown',
      // 请求ID
      requestId: generateUUID()
    };
    console.log('🔧 增强后的数据:', { 
        requestId: enhancedData.requestId,
        action: enhancedData.action,
        version: enhancedData.version,
        browser: enhancedData.browser,
        language: enhancedData.language
    });

    // 优先：转发到 Cloudflare Workers（写入 D1）
    const workerUrl = process.env.CLOUDFLARE_WORKER_URL; // e.g. https://adhdgofly-download-tracker.oliver-409.workers.dev/api/track-download
    const workerAuth = process.env.WORKER_AUTH_TOKEN;    // optional: Bearer token
    console.log('🔍 检查 Cloudflare Worker URL 配置:', { 
        hasWorkerUrl: !!workerUrl,
        workerUrl: workerUrl ? workerUrl.substring(0, 60) + '...' : '未设置'
    });
    
    if (workerUrl) {
      console.log('🔍 尝试转发到 Cloudflare Worker:', workerUrl); // 添加调试日志
      try {
        await storeToCloudflare(enhancedData, workerUrl, workerAuth);
        console.log('✅ 成功转发到 Cloudflare Worker');
      } catch (error) {
        console.error('Cloudflare storage failed:', error.message);
        // 不中断流程，继续后续步骤
      }
    } else {
        console.warn('⚠️ 未配置 Cloudflare Worker URL，跳过转发');
    }

    // 可选：存储到 GitHub (如果配置了 GITHUB_TOKEN)
    const githubToken = process.env.GITHUB_TOKEN;
    const enableGitHubBackup = (process.env.ENABLE_GITHUB_BACKUP || '').toLowerCase() === 'true';
    if (enableGitHubBackup && githubToken) {
      try {
        await storeToGitHub(enhancedData, githubToken);
      } catch (error) {
        console.error('GitHub storage failed:', error);
        // 不影响主要功能，继续执行
      }
    }

    // 记录到 Vercel 日志 (免费且永久可查)
    console.log('ADHDGoFly Data:', JSON.stringify(enhancedData, null, 2));

    // 返回成功响应
    return res.status(200).json({
      success: true,
      message: 'Data collected successfully',
      requestId: enhancedData.requestId,
      timestamp: enhancedData.serverTimestamp
    });

  } catch (error) {
    console.error('Collection error:', error);
    
    return res.status(500).json({
      success: false,
      error: 'Internal server error',
      message: error.message
    });
  }
}

// 生成UUID
function generateUUID() {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
    const r = Math.random() * 16 | 0;
    const v = c == 'x' ? r : (r & 0x3 | 0x8);
    return v.toString(16);
  });
}

// 可选：存储到 GitHub Issues
async function storeToGitHub(data, token) {
  const owner = 'zuoguyoupan2023'; // 您的 GitHub 用户名
  const repo = 'ADHDGoFly-Plugin'; // 您的仓库名
  
  const issueTitle = `Data Collection - ${data.action} - ${new Date().toISOString().split('T')[0]}`;
  const issueBody = `
## ADHDGoFly Plugin Data Collection

**Action:** ${data.action}
**Timestamp:** ${data.timestamp}
**Server Timestamp:** ${data.serverTimestamp}
**Request ID:** ${data.requestId}

### User Information
- **IP:** ${data.userIP}
- **Country:** ${data.country}
- **City:** ${data.city}
- **User Agent:** ${data.userAgent}

### Additional Data
\`\`\`json
${JSON.stringify(data, null, 2)}
\`\`\`

---
*Auto-generated by ADHDGoFly Plugin Data Collection System*
  `;

  const fetch = (await import('node-fetch')).default;
  const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/issues`, {
    method: 'POST',
    headers: {
      'Authorization': `token ${token}`,
      'Content-Type': 'application/json',
      'User-Agent': 'ADHDGoFly-Plugin-Collector'
    },
    body: JSON.stringify({
      title: issueTitle,
      body: issueBody,
      labels: ['data-collection', 'auto-generated']
    })
  });

  if (!response.ok) {
    throw new Error(`GitHub API error: ${response.status}`);
  }

  return await response.json();
}

// 转发到 Cloudflare Worker（写入 D1）
async function storeToCloudflare(data, workerUrl, authToken) {
  console.log('📤 准备发送数据到 Cloudflare Worker:', { workerUrl, data }); // 添加调试日志
  
  // 规范化负载，避免泄露敏感信息
  const payload = {
    version: data.version,
    browser: data.browser,
    language: data.language,
    userAgent: data.userAgent,
    referrer: data.referrer,
    timestamp: data.timestamp,
    // 传递真实客户端IP（来自前端到 Vercel 的头），便于 Worker 去重
    clientIp: Array.isArray(data.userIP) ? data.userIP[0] : (data.userIP || 'unknown')
  };

  const headers = { 'Content-Type': 'application/json' };
  if (authToken) {
    headers['Authorization'] = `Bearer ${authToken}`;
  }

  console.log('📨 发送请求到 Cloudflare Worker...'); // 添加调试日志
  const response = await fetch(workerUrl, {
    method: 'POST',
    headers,
    body: JSON.stringify(payload)
  });
  console.log('📨 请求完成，响应状态:', response.status); // 添加调试日志

  if (!response.ok) {
    const text = await response.text().catch(() => '');
    console.error('❌ Cloudflare Worker 响应错误:', { status: response.status, text }); // 添加调试日志
    throw new Error(`Worker API error: ${response.status} ${text}`);
  }

  return await response.json().catch(() => ({}));
}