// Vercel Serverless Function for ADHDGoFly Plugin Data Collection
// 支持自定义域名，避免被墙问题

export default async function handler(req, res) {
  // 设置 CORS 头，允许跨域访问
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');

  // 处理 OPTIONS 预检请求
  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  // 只允许 POST 请求
  if (req.method !== 'POST') {
    return res.status(405).json({
      success: false,
      error: 'Method not allowed'
    });
  }

  try {
    // 解析请求数据
    const data = req.body;
    
    // 数据验证
    if (!data.action || !data.timestamp) {
      return res.status(400).json({
        success: false,
        error: 'Missing required fields: action, timestamp'
      });
    }

    // 增强数据收集
    const enhancedData = {
      ...data,
      // 服务器时间戳
      serverTimestamp: new Date().toISOString(),
      // 用户IP (Vercel 提供)
      userIP: req.headers['x-forwarded-for'] || 
              req.headers['x-real-ip'] || 
              req.connection?.remoteAddress ||
              'unknown',
      // 用户代理
      userAgent: req.headers['user-agent'] || 'unknown',
      // 地理位置 (Vercel 提供)
      country: req.headers['x-vercel-ip-country'] || 'unknown',
      city: req.headers['x-vercel-ip-city'] || 'unknown',
      // 请求ID
      requestId: generateUUID()
    };

    // 可选：存储到 GitHub (如果配置了 GITHUB_TOKEN)
    const githubToken = process.env.GITHUB_TOKEN;
    if (githubToken) {
      try {
        await storeToGitHub(enhancedData, githubToken);
      } catch (error) {
        console.error('GitHub storage failed:', error);
        // 不影响主要功能，继续执行
      }
    }

    // 记录到 Vercel 日志 (免费且永久可查)
    console.log('ADHDGoFly Data:', JSON.stringify(enhancedData, null, 2));

    // 返回成功响应
    return res.status(200).json({
      success: true,
      message: 'Data collected successfully',
      requestId: enhancedData.requestId,
      timestamp: enhancedData.serverTimestamp
    });

  } catch (error) {
    console.error('Collection error:', error);
    
    return res.status(500).json({
      success: false,
      error: 'Internal server error',
      message: error.message
    });
  }
}

// 生成UUID
function generateUUID() {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
    const r = Math.random() * 16 | 0;
    const v = c == 'x' ? r : (r & 0x3 | 0x8);
    return v.toString(16);
  });
}

// 可选：存储到 GitHub Issues
async function storeToGitHub(data, token) {
  const owner = 'zuoguyoupan2023'; // 您的 GitHub 用户名
  const repo = 'ADHDGoFly-Plugin'; // 您的仓库名
  
  const issueTitle = `Data Collection - ${data.action} - ${new Date().toISOString().split('T')[0]}`;
  const issueBody = `
## ADHDGoFly Plugin Data Collection

**Action:** ${data.action}
**Timestamp:** ${data.timestamp}
**Server Timestamp:** ${data.serverTimestamp}
**Request ID:** ${data.requestId}

### User Information
- **IP:** ${data.userIP}
- **Country:** ${data.country}
- **City:** ${data.city}
- **User Agent:** ${data.userAgent}

### Additional Data
\`\`\`json
${JSON.stringify(data, null, 2)}
\`\`\`

---
*Auto-generated by ADHDGoFly Plugin Data Collection System*
  `;

  const fetch = (await import('node-fetch')).default;
  const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/issues`, {
    method: 'POST',
    headers: {
      'Authorization': `token ${token}`,
      'Content-Type': 'application/json',
      'User-Agent': 'ADHDGoFly-Plugin-Collector'
    },
    body: JSON.stringify({
      title: issueTitle,
      body: issueBody,
      labels: ['data-collection', 'auto-generated']
    })
  });

  if (!response.ok) {
    throw new Error(`GitHub API error: ${response.status}`);
  }

  return await response.json();
}